const data = [
  {type:'铝板',classify:[
  {serise:'1系',texture:'工业纯铝',e_t:'ONE',product:[
    {
      name:'1050',
      ply:['H12','H14']
    },
    {
      name:'1060',
      ply:['H14','H24']
    }
  ]},
  {serise:'2系',texture:'军工硬铝',e_t:'TWO',product:[
      {
          name:'2017',
          ply:['T3','T4']
      },
      {
          name:'2024',
          ply:['T3','T4']
      },
      {
          name:'2A12',
          ply:['T3','T4']
      }
  ]},
  {serise:'3系',texture:'防锈铝合金',e_t:'THREE',product:[
      {
          name:'3003',
          
          ply:['H14','H24']
      },
      {
          name:'3A21',
          ply:['H14','H112']
      }
  ]},
  {serise:'5系',texture:'耐腐蚀铝镁合金',e_t:'FIVE',product:[
      {
          name:'5052',
          ply:['H32','H112']
      },
      {
          name:'5083',
          ply:['O','H112']
      },
      {
          name:'5754',
          ply:['H22','H111']
      },
      {
          name:'5A02',
          ply:['O','H112']
      },
      {
          name:'5A05',
          ply:['O','H112']
      },
      {
          name:'5A06',
          ply:['O','H112']
      }
  ]},
  {serise:'6系',texture:'工业硬铝',e_t:'SIX',product:[
      {
          name:'6061',
          ply:['T6','T651']
      },
      {
          name:'6063',
          ply:['T6','T651']
      },
      {
          name:'6082',
          ply:['T6','T651']
      }
  ]},
  {serise:'7系',texture:'航空超硬铝',e_t:'SEVEN',product:[
      {
          name:'7050',
          ply:['T7451']
      },
      {
          name:'7075',
          ply:['T6','T651']
      },
      {
          name:'7A04',
          ply:['T6','T651']
      },
      {
          name:'7A09',
          ply:['T6','T651']
      }
  ]}
]},
{type:'铝棒',
  classify:[
  {serise:'1系',texture:'工业纯铝',e_t:'ONE',product:[
      {
          name:'1050',
          ply:['O','H112']
      },
      {
          name:'1060',
          ply:['O','H112']
      }
  ]},
  {serise:'2系',texture:'军工硬铝',e_t:'TWO',product:[
      {
          name:'2017',
          ply:['T3','T4']
      },
      {
          name:'2024',
          ply:['T3','T4']
      },
      {
          name:'2A12',
          ply:['T3','T4']
      }
  ]},
  {serise:'3系',texture:'防锈铝合金',e_t:'THREE',product:[
      {
          name:'3003',
          ply:['O','H112']
      },
      {
          name:'3A21',
          ply:['O','H112']
      }
  ]},
  {serise:'5系',texture:'耐腐蚀铝镁合金',e_t:'FIVE',product:[
      {
          name:'5052',
          ply:['O','H112']
      },
      {
          name:'5083',
          ply:['O','H112']
      },
      {
          name:'5754',
          ply:['O','H111']
      },
      {
          name:'5A02',
          ply:['O','H112']
      },
      {
          name:'5A05',
          ply:['O','H112']
      },
      {
          name:'5A06',
          ply:['O','H112']
      }
  ]},
  {serise:'6系',texture:'工业硬铝',e_t:'SIX',product:[
      {
          name:'6061',
          ply:['T6','T651']
      },
      {
          name:'6063',
          ply:['T6','T651']
      },
      {
          name:'6082',
          ply:['T6','T651']
      }
  ]},
  {serise:'7系',texture:'航空超硬铝',e_t:'SEVEN',product:[
      {
          name:'7050',
          ply:['T6','T651']
      },
      {
          name:'7075',
          ply:['T6','T651']
      },
      {
          name:'7A04',
          ply:['T6','T651']
      },
      {
          name:'7A09',
          ply:['T6','T651']
      }
  ]}
]},
{type:'铝卷',
  classify:[
  {serise:'1系',texture:'工业纯铝',e_t:'ONE',product:[
      {
          name:'1050',
          ply:['H14','H24']
      },
      {
          name:'1060',
          ply:['H14','H24']
      },
  ]},
  {serise:'2系',texture:'军工硬铝',e_t:'TWO',product:[
      {
          name:'2024',
          ply:['T3','T4']
      },
      {
          name:'2A12',
          ply:['O','T4']
      }
  ]},
  {serise:'3系',texture:'防锈铝合金',e_t:'THREE',product:[
      {
          name:'3003',
          ply:['H14','H24']
      },
      {
          name:'3A21',
          ply:['O','H24']
      }
  ]},
  {serise:'5系',texture:'耐腐蚀铝镁合金',e_t:'FIVE',product:[
      {
          name:'5052',
          ply:['O','H32']
      },
      {
          name:'5083',
          ply:['O','H111']
      },
      {
          name:'5754',
          ply:['H22','H111']
      },
      {
          name:'5A02',
          ply:['O','H32']
      }
  ]},
  {serise:'6系',texture:'工业硬铝',e_t:'SIX',product:[
      {
          name:'6061',
          ply:['O','T6']
      },
      {
          name:'6063',
          ply:['O','T6']
      }
  ]},
  {serise:'7系',texture:'航空超硬铝',e_t:'SEVEN',product:[
      {
          name:'7075',
          ply:['O','T6']
      }
  ]}
]},
{type:'铝管',
  classify:[
  {serise:'1系',texture:'工业纯铝',e_t:'ONE',product:[
      {
          name:'1050',
          ply:['O','H112']
      },
      {
          name:'1060',
          ply:['O','H112']
      }
  ]},
  {serise:'2系',texture:'军工硬铝',e_t:'TWO',product:[
      {
          name:'2017',
          ply:['T3','T4']
      },
      {
          name:'2024',
          ply:['T3','T4']
      },
      {
          name:'2A12',
          ply:['T4','T112']
      }
  ]},
  {serise:'3系',texture:'防锈铝合金',e_t:'THREE',product:[
      {
          name:'3003',
          ply:['O','H112']
      },
      {
          name:'3A21',
          ply:['O','H112']
      }
  ]},
  {serise:'5系',texture:'耐腐蚀铝镁合金',e_t:'FIVE',product:[
      {
          name:'5052',
          ply:['O','H112']
      },
      {
          name:'5083',
          ply:['O','H112']
      },
      {
          name:'5754',
          ply:['O','H112']
      },
      {
          name:'5A02',
          ply:['O','H112']
      },
      {
          name:'5A05',
          ply:['O','H112']
      },
      {
          name:'5A06',
          ply:['O','H112']
      }
  ]},
  {serise:'6系',texture:'工业硬铝',e_t:'SIX',product:[
      {
          name:'6061',
          ply:['T5','T6']
      },
      {
          name:'6063',
          ply:['T5','T6']
      },
      {
          name:'6082',
          ply:['T6','T651']
      }
  ]},
  {serise:'7系',texture:'航空超硬铝',e_t:'SEVEN',product:[
      {
          name:'7050',
          ply:['T6','T651']
      },
      {
          name:'7075',
          ply:['T6','T651']
      },
      {
          name:'7A04',
          ply:['T6','T651']
      },
      {
          name:'7A09',
          ply:['T6','T651']
      }
  ]}
]},
{type:'铝型材',
  classify:[
  {serise:'1系',texture:'工业纯铝',e_t:'ONE',product:[
      {
          name:'1050',
          ply:['H111','H112']
      },
      {
          name:'1060',
          ply:['H24','H112']
      }
  ]},
  {serise:'2系',texture:'军工硬铝',e_t:'TWO',product:[
      {
          name:'2017',
          ply:['T3','T4']
      },
      {
          name:'2024',
          ply:['T3','T4']
      },
      {
          name:'2A12',
          ply:['T4','T112']
      }
  ]},
  {serise:'3系',texture:'防锈铝合金',e_t:'THREE',product:[
      {
          name:'3003',
          ply:['H16','H112']
      },
      {
          name:'3A21',
          ply:['H18','H24']
      }
  ]},
  {serise:'5系',texture:'耐腐蚀铝镁合金',e_t:'FIVE',product:[
      {
          name:'5052',
          ply:['O','H112']
      },
      {
          name:'5083',
          ply:['H26','H112']
      },
      {
          name:'5754',
          ply:['H32','H112']
      },
      {
          name:'5A02',
          ply:['H32','H112']
      },
      {
          name:'5A05',
          ply:['O','H112']
      },
      {
          name:'5A06',
          ply:['O','H112']
      }
  ]},
  {serise:'6系',texture:'工业硬铝',e_t:'SIX',product:[
      {
          name:'6061',
          ply:['T5','T652']
      },
      {
          name:'6063',
          ply:['T5','T6']
      },
      {
          name:'6082',
          ply:['T6','T651']
      }
  ]},
  {serise:'7系',texture:'航空超硬铝',e_t:'SEVEN',product:[
      {
          name:'7050',
          ply:['T6','T651']
      },
      {
          name:'7075',
          ply:['T6','T651']
      },
      {
          name:'7A04',
          ply:['T6','T651']
      },
      {
          name:'7A09',
          ply:['T6','T651']
      }
  ]}
]},
{type:'铝锻件',
  classify:[
  {serise:'1系',texture:'工业纯铝',e_t:'ONE',product:[
      {
          name:'1050',
          ply:['H111','H112']
      },
      {
          name:'1060',
          ply:['H24','H112']
      }
  ]},
  {serise:'2系',texture:'军工硬铝',e_t:'TWO',product:[
      {
          name:'2017',
          ply:['T3','T4']
      },
      {
          name:'2024',
          ply:['T3','T4']
      },
      {
          name:'2A12',
          ply:['T4','T112']
      }
  ]},
  {serise:'3系',texture:'防锈铝合金',e_t:'THREE',product:[
      {
          name:'3003',
          ply:['H16','H112']
      },
      {
          name:'3A21',
          texture:'防锈铝合金',
          ply:['H18','H24']
      }
  ]},
  {serise:'5系',texture:'耐腐蚀铝镁合金',e_t:'FIVE',product:[
      {
          name:'5052',
          ply:['O','H112']
      },
      {
          name:'5083',
          ply:['H26','H112']
      },
      {
          name:'5754',
          ply:['H32','H112']
      },
      {
          name:'5A02',
          ply:['H32','H112']
      },
      {
          name:'5A05',
          ply:['O','H112']
      },
      {
          name:'5A06',
          ply:['O','H112']
      }
  ]},
  {serise:'6系',texture:'工业硬铝',e_t:'SIX',product:[
      {
          name:'6061',
          ply:['T5','T652']
      },
      {
          name:'6063',
          ply:['T5','T6']
      },
      {
          name:'6082',
          ply:['T6','T651']
      }
  ]},
  {serise:'7系',texture:'航空超硬铝',e_t:'SEVEN',product:[
      {
          name:'7050',
          ply:['T6','T651']
      },
      {
          name:'7075',
          ply:['T6','T651']
      },
      {
          name:'7A04',
          ply:['T6','T651']
      },
      {
          name:'7A09',
          ply:['T6','T651']
      }
  ]}
]}
]
export default function getProductList(req,res){
const {categoryIndex,typeIndex,seriseIndex} = req.body
console.log(categoryIndex,typeIndex,seriseIndex);
// 一级请求
if(categoryIndex !== undefined && (typeIndex == undefined && seriseIndex ==undefined)){
// console.log('一级请求');
let list = data[categoryIndex]
// data[categoryIndex].first_classify.forEach(item=> {
//     list.push(item.type)
// });
// console.log(list);
res.status(200).json({list})
}
}